# Generated by Codex on 2026-04-19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.CharField(blank=True, default="Клиент", max_length=255, null=True)),
                ("body", models.TextField()),
                ("avatar_path", models.TextField(blank=True, null=True)),
                ("image_path", models.TextField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("sort", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["sort", "-created_at"],
            },
        ),
    ]
