# Generated by Codex on 2026-04-19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=64, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "new"), ("in_progress", "in_progress"), ("done", "done")],
                        db_index=True,
                        default="new",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-created_at"],
            },
        ),
    ]
